# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
r:
  - release
  - oldrel
  - devel
matrix:
  include:
    - r: release
      os: linux
      after_success:
       - Rscript -e 'devtools::install_github("r-lib/pkgdown")'
       - Rscript -e 'pkgdown::build_site()'
       - Rscript -e 'covr::codecov()'
  exclude:
    - r: devel
      os: osx
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: ${TRAVIS_BUILD_DIR}/docs
