# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
r:
  - oldrel
  - devel
matrix:
  include:
    - r: release
      os: linux
      after_success:
       - Rscript after.R
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_PAT
        on:
          branch: master
        local_dir: docs
        target_branch: gh-pages
    - r: release
      os: osx
  exclude:
    - r: devel
      os: osx

